spring:
  application:
    name: TASK-SERVICE
  datasource:
    url: jdbc:postgresql://34.124.162.41/miniproject2
    username: user
    password: 1111
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://keycloak.domrra.site/auth/realms/mini-project-2-realm
          jwk-set-uri: https://keycloak.domrra.site/auth/realms/mini-project-2-realm/protocol/openid-connect/certs
keycloak:
  realm: mini-project-2-realm
  resource: mini-project-2-client
  auth-server-url: https://keycloak.domrra.site/auth/ #docker container
  credentials:
    username: 'admin'
    password: 'admin'
    client-id: 'mini-project-2-client'
    secret: 'LdBQdeV2CO3uUdiSi0CbZkU0rA9gAibQ'
    provider: secret
logging:
  level:
    org.springframework.web: debug






# config Eureka
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9001/eureka
server:
  port: 2001